set -gx fish_color_autosuggestion:767676
set -gx fish_color_cancel:\x2dr
set -gx fish_color_command:normal
set -gx fish_color_comment:767676
set -gx fish_color_cwd:green
set -gx fish_color_cwd_root:red
set -gx fish_color_end:ffffff
set -gx fish_color_error:ffffff
set -gx fish_color_escape:bryellow\x1e\x2d\x2dbold
set -gx fish_color_history_current:\x2d\x2dbold
set -gx fish_color_host:normal
set -gx fish_color_match:\x2d\x2dbackground\x3dbrblue
set -gx fish_color_normal:normal
set -gx fish_color_operator:bryellow
set -gx fish_color_param:ffffff
set -gx fish_color_quote:ffffff
set -gx fish_color_redirection:ffffff
set -gx fish_color_search_match:bryellow\x1e\x2d\x2dbackground\x3dbrblack
set -gx fish_color_selection:white\x1e\x2d\x2dbold\x1e\x2d\x2dbackground\x3dbrblack
set -gx fish_color_status:red
set -gx fish_color_user:brgreen
set -gx fish_color_valid_path:\x2d\x2dunderline
set -gx fish_greeting:Welcome\x20to\x20fish\x2c\x20the\x20friendly\x20interactive\x20shell
set -gx fish_key_bindings:fish_default_key_bindings
set -gx fish_pager_color_completion:\x1d
set -gx fish_pager_color_description:B3A06D\x1eyellow
set -gx fish_pager_color_prefix:white\x1e\x2d\x2dbold\x1e\x2d\x2dunderline
set -gx fish_pager_color_progress:brwhite\x1e\x2d\x2dbackground\x3dcyan
